export function load(event) {
  return {
    list: [
      {
        chapter_id: 1,
        id: 1,
        title: "이세계에서 치트능력을 손에 넣은 나는, 현실세계에서도 무쌍한다",
        latest_chapter: "2화 【1일 1개, 신기한 나무열매】편",
        modified: "2024-12-18",
      },
      {
        chapter_id: 2,
        id: 2,
        title: "너와 나의 마지막 전장, 혹은 세계가 시작되는 성전",
        latest_chapter: "5화 【별빛 아래의 결투】",
        modified: "2024-12-17",
      },
      {
        chapter_id: 3,
        id: 3,
        title: "무직전생 ~이세계에 갔으면 최선을 다한다~",
        latest_chapter: "9화 【신기술, 지상강타】",
        modified: "2024-12-15",
      },
      {
        chapter_id: 4,
        id: 4,
        title: "데이트 어 라이브",
        latest_chapter: "12화 【시간의 여신과의 만남】",
        modified: "2024-12-14",
      },
      {
        chapter_id: 5,
        id: 5,
        title: "소드 아트 온라인",
        latest_chapter: "15화 【고대의 미궁】",
        modified: "2024-12-13",
      },
      {
        chapter_id: 6,
        id: 6,
        title: "던전에서 만남을 추구하면 안 되는 걸까",
        latest_chapter: "18화 【흑사자의 분노】",
        modified: "2024-12-12",
      },
      {
        chapter_id: 7,
        id: 7,
        title: "귀여운 여동생에게 속아서 위험한 저택에 갇혔다",
        latest_chapter: "6화 【저택의 수수께끼를 풀다】",
        modified: "2024-12-11",
      },
      {
        chapter_id: 8,
        id: 8,
        title: "Re:제로부터 시작하는 이세계 생활",
        latest_chapter: "20화 【절망의 끝에서】",
        modified: "2024-12-10",
      },
      {
        chapter_id: 9,
        id: 9,
        title: "현자의 손자",
        latest_chapter: "7화 【성왕의 선택】",
        modified: "2024-12-09",
      },
      {
        chapter_id: 10,
        id: 10,
        title: "전생했더니 슬라임이었던 건에 대하여",
        latest_chapter: "13화 【마물들의 도시】",
        modified: "2024-12-08",
      },
      {
        chapter_id: 11,
        id: 11,
        title: "오버로드",
        latest_chapter: "22화 【왕국의 몰락】",
        modified: "2024-12-07",
      },
      {
        chapter_id: 12,
        id: 12,
        title: "이세계 마왕과 소환 소녀의 노예 마술",
        latest_chapter: "8화 【마족의 강림】",
        modified: "2024-12-06",
      },
      {
        chapter_id: 13,
        id: 13,
        title: "겁쟁이 페달",
        latest_chapter: "30화 【끝없는 경주】",
        modified: "2024-12-05",
      },
    ],
  };
}
